# Generated by Django 4.0.1 on 2022-01-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroherd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='telefone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='cep',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='documento',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
