# Generated by Django 4.0.1 on 2022-01-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroherd', '0004_paciente_convenio_alter_filaenfermagem_paciente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(blank=True, choices=[('senapred', 'SENAPRED'), ('comad', 'COMAD'), ('sem', 'Sem convênio')], max_length=10),
        ),
    ]
