# Generated by Django 4.0.1 on 2022-01-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centroherd', '0005_alter_paciente_convenio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='convenio',
            field=models.CharField(choices=[('senapred', 'SENAPRED'), ('comad', 'COMAD'), ('sem', 'Sem convênio')], max_length=10),
        ),
    ]
