# Generated by Django 4.0.1 on 2022-02-04 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centroherd', '0007_remove_social_acompanhamento_paciente_cartao_sus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='unidade',
            field=models.CharField(choices=[('1', 'Unidade 1'), ('2', 'Unidade 2')], default=1, max_length=2),
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acompanhamento', models.TextField(blank=True)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroherd.paciente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medicina - Prontuario',
            },
        ),
        migrations.CreateModel(
            name='FilaMedicina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado', models.DateField(auto_now_add=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroherd.paciente', unique=True)),
            ],
            options={
                'verbose_name': 'Fila - Medicina',
                'verbose_name_plural': 'Fila - Medicina',
            },
        ),
    ]