# Generated by Django 4.0.1 on 2022-02-21 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('centroherd', '0008_paciente_unidade_medicina_filamedicina'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psicologia',
            old_name='acompanhamento',
            new_name='alimentacao',
        ),
        migrations.AddField(
            model_name='psicologia',
            name='agressividade',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='alucinacao_com_droga',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='alucinacao_sem_droga',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='condicoes_moradia',
            field=models.CharField(blank=True, choices=[('so', 'So'), ('pais', 'Pais'), ('familiares', 'Esposa/Filhos'), ('alojamento', 'Alojamento'), ('amigos', 'Amigos'), ('parentes', 'Parentes'), ('outros', 'Outros')], max_length=15),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='critica_situacao',
            field=models.CharField(blank=True, choices=[('excelente', 'Excelente'), ('muito_bom', 'Muito Bom(a)'), ('bom', 'Bom(a)'), ('razoavel', 'Razoavel'), ('ruim', 'Ruim'), ('pessimo', 'Péssimo(a)')], max_length=20),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='demanda_atendimento',
            field=models.CharField(blank=True, choices=[('propria', 'Propria'), ('familiares', 'Familiares'), ('amigos', 'Amigos'), ('empresa', 'Empresa')], max_length=20),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='desemprego',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='desmaio_convulcao_com_droga',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='desmaio_convulcao_sem_droga',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='dificuldade_de_gerir_propria_vida',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='dificuldade_ter_manter_vinculos_sociais',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='droga_intravenosa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='fatores_de_protecao_e_prognosticos_da_dependencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='fatores_de_risco_e_mantenedores_da_dependencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='frequencia_consumo_ultimos_meses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='frequencia_e_locais',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='hipoteses_diagnosticas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='metas_atividades_terapeuticas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='motivo_demanda',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='outros_sintomas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='overdose_droga_e_frequencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='overdose_por_essas_drogas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='parecer_tecnico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='problemas_ambiente_trabalho',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='problemas_familiares',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='problemas_legais_juridicos_existentes_ou_pendentes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='quais_medicacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='quais_problemas_legais_juridicos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='quantidade_consumida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='reacoes_da_droga',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='saude',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='se_empresa',
            field=models.CharField(blank=True, choices=[('testagem', 'Testagem Positiva'), ('espontanea', 'Demanda Espontanea'), ('servico_saude', 'Demanda Serviço Saúde')], max_length=20),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='sintoma_ao_chegar',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='situacao_atual',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='situacao_que_faz_o_uso',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='sono',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='tempo_abstitencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='toma_alguma_medicacao',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='tratamento_anterior',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='ultimo_episodio_de_consumo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='usuario_espera_tratamento',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='psicologia',
            name='via_administracao_escolhida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='TratamentosAnteriores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tratamento', models.CharField(choices=[('psiquiatrico', 'Psiquiatrico'), ('medico_clinico', 'Medico Clinico'), ('psicoterapico', 'Psicoterapico'), ('psicanalitico', 'Psicanalitico'), ('grupo_ajuda_mutua', 'Grupo de Ajuda Mútua'), ('religioso', 'Religioso'), ('comunidade_terapeutica', 'Comunidade Terapeutica'), ('outros', 'Outros')], max_length=100)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('psicologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroherd.psicologia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tratamentos Anteriores',
            },
        ),
        migrations.CreateModel(
            name='Sintomas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sintomas', models.CharField(choices=[('tosse', 'Tosse'), ('dispneia', 'Dispenia/Falta de ar'), ('dor', 'Dor'), ('febre', 'Febre'), ('emagrecimento', 'Emagrecimento'), ('lesao_da_pele', 'Lesao da Pele'), ('diarreia', 'Diarreia'), ('nausea_vomito', 'Nausea/Vomito'), ('fraqueza', 'Fraqueza Muscular'), ('tremores', 'Tremores'), ('dificuldade_locomocao', 'Dificuldade de locomoção'), ('outros', 'Outros')], max_length=100)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('psicologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroherd.psicologia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sintomas',
            },
        ),
        migrations.CreateModel(
            name='SinalizadoresProblematicosDescorrentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sinalizadores_problematicos_decorrentes_ao_uso', models.CharField(choices=[('faltas_frequentes', 'Faltas Frequentes no trabalho'), ('depressao', 'Depressao'), ('historia_de_trauma', 'Historia de Trauma'), ('ansiedade', 'Ansiedade'), ('hipertensao', 'Hipertensao'), ('sintoma_gastro', 'Sintoma GastroIntestinal'), ('disturbio_sono', 'Disturbio do sono'), ('disfuncao_sexual', 'Disfunção Sexual'), ('hemorragias', 'Hemorragias')], max_length=100)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('psicologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroherd.psicologia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sinalizadores Problematicos Decorrentes ao uso de alcool e drogas',
            },
        ),
        migrations.CreateModel(
            name='HistoricoDrogaPsicologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('droga', models.CharField(choices=[('alcool', 'Alcool'), ('crack', 'Crack'), ('maconha', 'Maconha/Haxixe'), ('cocaina', 'Cocaina'), ('inalante', 'Inalante/Cola'), ('diazepan', 'Diazepan'), ('anfetamina', 'Anfetamina/Remedio p/ Emagrecer'), ('ecstasy', 'Ecstasy/MDMA'), ('lsd', 'LSD'), ('heroina', 'Heroina'), ('tabaco', 'Tabaco'), ('outros', 'Outros')], max_length=100)),
                ('idade_primeiro_uso', models.BigIntegerField()),
                ('idade_ultima_vez', models.BigIntegerField()),
                ('frenquencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('mensal', 'Mensal'), ('fds', 'Fim de Semana')], max_length=100)),
                ('quando_usa', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], max_length=100)),
                ('vias_de_uso', models.CharField(choices=[('oral', 'Oral'), ('inalada', 'Inalada'), ('fumada', 'Fumada'), ('injetada', 'Injetada')], max_length=100)),
                ('quantidade', models.BigIntegerField()),
                ('observacoes', models.TextField(blank=True)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('psicologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroherd.psicologia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Histórico de Drogas',
            },
        ),
        migrations.CreateModel(
            name='AmbientesConsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambientes_consumo', models.CharField(choices=[('festas', 'Festas'), ('rua', 'Rua'), ('amigos', 'Amigos'), ('casa', 'Casa'), ('trabalho', 'Trabalho'), ('com_desconhecidos', 'Com Desconhecidos'), ('sozinho', 'Sozinho')], max_length=100)),
                ('criado', models.DateField(auto_now_add=True)),
                ('atualizado', models.DateField(auto_now=True)),
                ('psicologia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centroherd.psicologia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Ambientes de Consumo',
            },
        ),
    ]
